<?php
/**
 * Created by PhpStorm.
 * User: danny
 * Date: 19/07/15
 * Time: 03:46 PM
 */
class Main extends CI_Controller{
    /**
     * @var User_standard Variable que tiene la estructura del estandar proporcionado por el usuario
     */
    private $standard;

    private $collection_sub_helper;
/**
 * Constructor
 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->library('encrypt');
        $this->load->library("User_standard");
        $this->load->library("Collection_subcollection_helper");
        $this->load->model("admin_model");
        $this->load->model("main_model");
        $this->standard = new User_standard();
        $this->collection_sub_helper = new Collection_subcollection_helper();
    }

    public function index(){
        if($this->session->userdata('logged_in')){
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show(),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "sessioninitialized" => "yes",
                "container_title" => "Objetos de Aprendizaje",
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show(),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "sessioninitialized" => "no",
                "container_title" => "Objetos de Aprendizaje",
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }


        $this->load->view("layouts/main_template", $content);
    }

    public function oas_objects_per_collection($id_collection)
    {
        if($this->session->userdata('logged_in')){
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "actualcollection" => $id_collection,
                "sessioninitialized" => "yes",
                "container_title" => $this->main_model->get_container_name($id_collection, "0"),
                "authorized_upload" => "yes",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "actualcollection" => $id_collection,
                "sessioninitialized" => "no",
                "container_title" => $this->main_model->get_container_name($id_collection, "0"),
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }

        $this->load->view("layouts/main_template", $content);
    }
    public function oas_objects_per_subcollection($id_collection, $id_subcollection)
    {
        if($this->session->userdata('logged_in')){
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection, $id_subcollection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "authorized_upload" => "yes",
                "container_title" => $this->main_model->get_container_name($id_collection, $id_subcollection),
                "listas" => "",
                "sessioninitialized" => "yes",
                "actualcollection" => $id_collection,
                "actualsubcollection" => $id_subcollection,
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection, $id_subcollection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "authorized_upload" => "no",
                "container_title" => $this->main_model->get_container_name($id_collection, $id_subcollection),
                "listas" => "",
                "sessioninitialized" => "no",
                "actualcollection" => $id_collection,
                "actualsubcollection" => $id_subcollection,
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }


        $this->load->view("layouts/main_template", $content);
    }

}