<?php
/**
 * Created by PhpStorm.
 * User: danny
 * Date: 19/07/15
 * Time: 03:46 PM
 */
class Main extends CI_Controller{
    /**
     * @var User_standard Variable que tiene la estructura del estandar proporcionado por el usuario
     */
    private $standard;
/**
 * Constructor
 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->library('encrypt');
        $this->load->library("User_standard");
        $this->load->model("admin_model");
        $this->standard = new User_standard();
    }

    public function index(){
        $content = array(
            "metadatos" => $this->standard->get_metadata_to_show(),
            "hide_metadatos" => $this->standard->get_show_hide_metadata(),
            "oas_user" => $this->standard->get_own_users_oas(),
            "listas" => "",
            "collections" => $this->admin_model->get_collections_list(),
            "subcollections" => $this->admin_model->get_subcollections_list(),
            "main" => "main/main_view"
        );

        $this->load->view("layouts/main_template", $content);
    }

}