<?php
/**
 * Created by PhpStorm.
 * User: danny
 * Date: 19/07/15
 * Time: 03:46 PM
 */
class Main extends CI_Controller{
    /**
     * @var User_standard Variable que tiene la estructura del estandar proporcionado por el usuario
     */
    private $standard;

    private $collection_sub_helper;
/**
 * Constructor
 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->library('encrypt');
        $this->load->library("User_standard");
        $this->load->library("Collection_subcollection_helper");
        $this->load->model("admin_model");
        $this->load->model("main_model");
        $this->standard = new User_standard();
        $this->collection_sub_helper = new Collection_subcollection_helper();
    }

    public function index(){
        if($this->session->userdata('logged_in')){
            $arr = $this->session->userdata('logged_in');
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show(),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "sessioninitialized" => "yes",
                "container_title" => "Objetos de Aprendizaje",
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view",
                "user_logged" => $arr["id"]
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show(),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "sessioninitialized" => "no",
                "container_title" => "Objetos de Aprendizaje",
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }


        $this->load->view("layouts/main_template", $content);
    }

    public function oas_objects_per_collection($id_collection)
    {
        if($this->session->userdata('logged_in')){
            $arr = $this->session->userdata('logged_in');
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "actualcollection" => $id_collection,
                "sessioninitialized" => "yes",
                "container_title" => $this->main_model->get_container_name($id_collection, "0"),
                "authorized_upload" => "yes",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view",
                "user_logged" => $arr["id"]
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "listas" => "",
                "actualcollection" => $id_collection,
                "sessioninitialized" => "no",
                "container_title" => $this->main_model->get_container_name($id_collection, "0"),
                "authorized_upload" => "no",
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"

            );
        }

        $this->load->view("layouts/main_template", $content);
    }
    public function oas_objects_per_subcollection($id_collection, $id_subcollection)
    {
        if($this->session->userdata('logged_in')){
            $arr = $this->session->userdata('logged_in');
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection, $id_subcollection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "authorized_upload" => "yes",
                "container_title" => $this->main_model->get_container_name($id_collection, $id_subcollection),
                "listas" => "",
                "sessioninitialized" => "yes",
                "actualcollection" => $id_collection,
                "actualsubcollection" => $id_subcollection,
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view",
                "user_logged" => $arr["id"],
            );
        }else{
            $content = array(
                "metadatos" => $this->standard->get_metadata_to_show($id_collection, $id_subcollection),
                "hide_metadatos" => $this->standard->get_show_hide_metadata(),
                "oas_user" => $this->standard->get_own_users_oas(),
                "authorized_upload" => "no",
                "container_title" => $this->main_model->get_container_name($id_collection, $id_subcollection),
                "listas" => "",
                "sessioninitialized" => "no",
                "actualcollection" => $id_collection,
                "actualsubcollection" => $id_subcollection,
                "collections" => $this->collection_sub_helper->get_collection_list(),
                "numoas_collection" => $this->collection_sub_helper->get_num_oas_collections(),
                "subcollections" => $this->collection_sub_helper->get_subcollection_list(),
                "numoas_subcollections" => $this->collection_sub_helper->get_num_oas_subcollections(),
                "main" => "main/main_view"
            );
        }


        $this->load->view("layouts/main_template", $content);
    }

    public function show_pagination_oas(){

    }

    public function search_oas($words){
        $stop_words = array("un","una","unas","unos","uno","sobre","todo","también","tras","otro","algún","alguno","alguna","algunos","algunas","ser","es","soy","eres","somos","sois","estoy","esta","estamos","estais","estan","como","en","para","atras","porque","porqué","estado","estaba","ante","antes","siendo","ambos","pero","por","poder","puede","puedo","podemos","podeis","pueden","fui","fue","fuimos","fueron","hacer","hago","hace","hacemos","haceis","hacen","cada","fin","incluso","primero","desde","conseguir","consigo","consigue","consigues","conseguimos","consiguen","ir","voy","va","vamos","vais","van","vaya","gueno","ha","tener","tengo","tiene","tenemos","teneis","tienen","el","la","lo","las","los","su","aqui","mio","tuyo","ellos","ellas","nos","nosotros","vosotros","vosotras","si","dentro","solo","solamente","saber","sabes","sabe","sabemos","sabeis","saben","ultimo","largo","bastante","haces","muchos","aquellos","aquellas","sus","entonces","tiempo","verdad","verdadero","verdadera","cierto","ciertos","cierta","ciertas","intentar","intento","intenta","intentas","intentamos","intentais","intentan","dos","bajo","arriba","encima","usar","uso","usas","usa","usamos","usais","usan","emplear","empleo","empleas","emplean","ampleamos","empleais","valor","muy","era","eras","eramos","eran","modo","bien","cual","cuando","donde","mientras","quien","con","entre","sin","trabajo","trabajar","trabajas","trabaja","trabajamos","trabajais","trabajan","podria","podrias","podriamos","podrian","podriais","yo","aquel");
        $words1 = str_replace($stop_words, "", strtolower(trim($words)));
        print_r($words);
        $words1 = preg_replace('/\s+/'," ", $words1);

        $words1 = str_replace(" ", ",",$words1);
        $words2 = explode("_", $words1);

        if($this->session->userdata('logged_in')){
            $arr = $this->session->userdata('logged_in');
            $content = array(
                "metadatossearch" => $this->standard->get_metadata_to_show("0", "0", $words2),
                "hide_metadatossearch" => $this->standard->get_show_hide_metadata(),
                "oas_usersearch" => $this->standard->get_own_users_oas(),
                "container_titlesearch" => "Busqueda",
                "user_logged" => $arr["id"],

            );
        }else{
            $content = array(
                "metadatossearch" => $this->standard->get_metadata_to_show("0", "0", $words2),
                "hide_metadatossearch" => $this->standard->get_show_hide_metadata(),
                "oas_usersearch" => $this->standard->get_own_users_oas(),
                "container_titlesearch" => "Busqueda",

            );
        }

        $this->load->view("main/main_search", $content);
    }

}